import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import ClientChatbot from "../components/ClientChatbot";
import { SidebarProvider } from "@/contexts/SidebarContext";
import TokenInitializer from "@/components/TokenInitializer";
import { AppLoader } from "@/components/AppLoader";
import { MobileAppDownload } from "@/components/MobileAppDownload";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <UserProvider>
            <AppLoader>
              <TokenInitializer />
              {children}
              <ClientChatbot />
              <MobileAppDownload />
              <Toaster position="top-right" />
            </AppLoader>
          </UserProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
